language:
  ruby

rvm:
  - '2.4'
  - '2.5'
  - '2.6'
  - ruby-head
  - jruby-9.1
  - jruby-head

env:
  - LINGO_BACKEND=LibCDB
  - LINGO_BACKEND=SDBM
  - LINGO_BACKEND=GDBM
  - LINGO_BACKEND=Hash

matrix:
  exclude:
    - rvm: jruby-9.1
      env: LINGO_BACKEND=LibCDB
    - rvm: jruby-head
      env: LINGO_BACKEND=LibCDB

  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-9.1
    - rvm: jruby-head

  fast_finish:
    true

script:
  rake test:all LINGO_DISABLE_SLOW_TESTS=1

install:
  - gem install nuggets power_assert
  - gem install libcdb-ruby || true  # no JRuby
  - gem install --prerelease --development lingo

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libcdb-dev

sudo:
  required

dist:
  trusty
